/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bisect.java;

import org.junit.jupiter.api.Test;

import static bisect.java.Bisect.bisect;
import static bisect.java.BisectResult.bisectResult;
import static bisect.java.Suspect.suspect;
import static bisect.java.Version.version;
import static com.google.common.truth.Truth8.assertThat;


class BisectTest {
    @Test
    void returnKnownBadIfAllPreviousVesionsAreGood() {
        BisectOutcome outcome = bisect(version("good"), version("bad"), new RecordingScene());
        assertThat(outcome.result).hasValue(bisectResult(suspect(version("good")), suspect(version("bad"))));
    }
}
