/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bisect.java;

import java.util.List;

public class Bisect {

    public static BisectOutcome bisect(Version knownGood, Version knownBad, Scene scene) {
        List<Suspect> suspects = scene.suspects();
        return BisectOutcome.result(new BisectResult(new Suspect(Version.version("good")), new Suspect(Version.version("bad"))));
    }

    public static void main(String[] args) {
    }
}
